### PR TITLE
Notebooks for v2 of the client

### PR DESCRIPTION
**Pull request by alexander-mead**

### CODE REVIEW

**Review by huylenguyen — CHANGES_REQUESTED** [review]
Just a couple of easy to fix errors:

02: spelling error in title (guassian)

03: under Functional Emulator Workflow - `decompose_inputs` and `decompose_outputs` missing trailing `s`'s

04: not a notebook error, and does not need to be handled right now, but doing `emulator.predict` multiple times in a loop on singleton datasets instead of creating just one dataset that contains multiple rows seem silly. It is very very slow to run this second to last cell. 

05: Not a notebook error, but model selection returns error `{'message': "'Result' object has no attribute '_local_path'"}`. Locally using `ray=2.8.0` in the library works fine, but cloud install must be on 2.9.0. Had a quick look through their source and something has indeed changed, which will improve our syntax if we upgrade but for now we should fix ray to 2.8.0 or 2.8.1

**Comment by alexander-mead** [comment]
This is great, and looks ready to go. Do you want me to implement those changes @huylenguyen?

**Review by huylenguyen — APPROVED** [review]
Looks good now! :)

**Comment by michellebieger** [comment]
We need to make sure that the v1 docs are still available! Need to check whether this needs to be done whilst this PR is open.

**Comment by michellebieger** [comment]
I know now how to update this in the documentation with the V1 notebooks included. Please do not merge.

**Pull request merged**
