### PR TITLE
Created Bayesian Optimisation notebook

### PR DESCRIPTION
**Pull request by SaiAakash**
Created a Bayesian Optimization notebook to demonstrate the functionality of the newly added `optimise_campaign` feature. The notebook steps through how the model trained on training data can be used to find the maxima of the unknown target function that generated the training data. The notebook has both 1D and 2D examples of this.

### CODE REVIEW

**Comment by alexander-mead** [comment]
Great. Can you provide some sort of description to guide the reviewer as to what you are doing with this?

**Comment by SaiAakash** [comment]
For 1D example we use the Forrester function. The GP very accurately finds the maximum. For 2D example we use a simple 2D quadratic function. This choice was made so that the visualisation is easy to interpret and more intuitive. Again, in this case the GP finds a good maximum candidate very close to the true maximum.

**Comment by huylenguyen** [comment]
> Great. Can you provide some sort of description to guide the reviewer as to what you are doing with this?

Mainly, a 2D heatmap is a nice option to have when demonstrating this functionality to potential users. Eventually it would be nice to have an example with a local maxima as well, but this needs more exploration time than we have for the current sprint.

**Review by huylenguyen — CHANGES_REQUESTED** [review]
Excellent work @SaiAakash. I'd like a couple of very minor changes to the notebook. you can tick these off here as you go:

- [x] remove unused `matplotlib` import at the top
- [x] For both 1D and 2D examples, run `optimise_campaign` a second time (and show plot). Optimisation is an iterative process, and we should not be giving the impression that this is something you do once per model (even though in these examples the model does find the correct maxima). Put some markdown to help the user understand this. 
- [x] Finally, after the above is done, unrun the notebook

**Comment by SaiAakash** [comment]
> Excellent work @SaiAakash. I'd like a couple of very minor changes to the notebook. you can tick these off here as you go:
> 
> * [x]  remove unused `matplotlib` import at the top
> * [x]  For both 1D and 2D examples, run `optimise_campaign` a second time (and show plot). Optimisation is an iterative process, and we should not be giving the impression that this is something you do once per model (even though in these examples the model does find the correct maxima). Put some markdown to help the user understand this.
> * [x]  Finally, after the above is done, unrun the notebook

Done !

**Review by huylenguyen — APPROVED** [review]
Excellent work!

**Pull request merged**
